-- ============================================================
-- MEDICORE HEALTH SYSTEMS - SNOWFLAKE DATA PLATFORM
-- ============================================================
-- Phase 06: Monitoring Views - Validation Test Suite
-- Script: 06_test_monitoring_views.sql
--
-- Description:
--   Non-destructive, read-only validation script that verifies
--   all Phase 06 monitoring view configurations are correct.
--   Designed for CI/CD automated verification after executing
--   06_monitoring_views.sql.
--
-- Safety:
--   - Contains ONLY SELECT, SHOW, DESCRIBE, and RESULT_SCAN queries
--   - Does NOT create, alter, drop, grant, or modify any objects
--   - Safe for production execution
--   - Idempotent
--
-- Execution Requirements:
--   - Must be run as ACCOUNTADMIN
--   - Execute AFTER 06_monitoring_views.sql
--   - Compatible with MEDICORE_SVC_GITHUB_ACTIONS
--
-- Test Coverage:
--   - View existence validation
--   - Schema location validation
--   - View definition validation
--   - Column validation
--   - Execution validation
--   - Security grant validation
--   - Negative tests (unauthorized access)
--   - Object count drift detection
--
-- Author: MediCore Platform Team
-- Date: 2026-02-25
-- ============================================================


USE ROLE ACCOUNTADMIN;


-- ============================================================
-- SECTION 1: VIEW EXISTENCE VALIDATION
-- ============================================================
-- Confirms all 8 required monitoring views exist.
-- ============================================================

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_001' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_WAREHOUSE_CREDIT_USAGE';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_002' AS TEST_ID,
    'V_QUERY_PERFORMANCE exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_QUERY_PERFORMANCE';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_003' AS TEST_ID,
    'V_LONG_RUNNING_QUERIES exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_LONG_RUNNING_QUERIES';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_004' AS TEST_ID,
    'V_FAILED_QUERIES exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_FAILED_QUERIES';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_005' AS TEST_ID,
    'V_RESOURCE_MONITOR_STATUS exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_RESOURCE_MONITOR_STATUS';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_006' AS TEST_ID,
    'V_WAREHOUSE_UTILIZATION exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_WAREHOUSE_UTILIZATION';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_007' AS TEST_ID,
    'V_ACTIVE_WAREHOUSE_LOAD exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_ACTIVE_WAREHOUSE_LOAD';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_008' AS TEST_ID,
    'V_COST_BY_WAREHOUSE_MONTH exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_COST_BY_WAREHOUSE_MONTH';


-- ============================================================
-- SECTION 2: SCHEMA VALIDATION
-- ============================================================
-- Confirms all views are in MEDICORE_GOVERNANCE_DB.AUDIT.
-- ============================================================

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_009' AS TEST_ID,
    'All views in correct schema (AUDIT)' AS TEST_NAME,
    '8' AS EXPECTED_VALUE,
    COUNT(*)::VARCHAR AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 8 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "schema_name" = 'AUDIT'
  AND "database_name" = 'MEDICORE_GOVERNANCE_DB'
  AND "name" LIKE 'V_%';


-- ============================================================
-- SECTION 3: VIEW DEFINITION VALIDATION
-- ============================================================
-- Confirms views reference SNOWFLAKE.ACCOUNT_USAGE.
-- ============================================================

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_010' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE references ACCOUNT_USAGE' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE WHEN "text" LIKE '%ACCOUNT_USAGE%' THEN 'CONTAINS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN "text" LIKE '%ACCOUNT_USAGE%' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_WAREHOUSE_CREDIT_USAGE';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_011' AS TEST_ID,
    'V_QUERY_PERFORMANCE references ACCOUNT_USAGE' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE WHEN "text" LIKE '%ACCOUNT_USAGE%' THEN 'CONTAINS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN "text" LIKE '%ACCOUNT_USAGE%' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_QUERY_PERFORMANCE';

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_012' AS TEST_ID,
    'V_RESOURCE_MONITOR_STATUS references ACCOUNT_USAGE' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE WHEN "text" LIKE '%ACCOUNT_USAGE%' THEN 'CONTAINS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN "text" LIKE '%ACCOUNT_USAGE%' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'V_RESOURCE_MONITOR_STATUS';


-- ============================================================
-- SECTION 4: COLUMN VALIDATION
-- ============================================================
-- Validates required columns exist in each view.
-- ============================================================

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_013' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE has WAREHOUSE_NAME column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'WAREHOUSE_NAME';

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_014' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE has TOTAL_CREDITS column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'TOTAL_CREDITS';

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_015' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE has CREATED_AT column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'CREATED_AT';

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_QUERY_PERFORMANCE;

SELECT
    'TC_06_016' AS TEST_ID,
    'V_QUERY_PERFORMANCE has QUERY_ID column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'QUERY_ID';

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_QUERY_PERFORMANCE;

SELECT
    'TC_06_017' AS TEST_ID,
    'V_QUERY_PERFORMANCE has EXECUTION_TIME_SECONDS column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'EXECUTION_TIME_SECONDS';

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_RESOURCE_MONITOR_STATUS;

SELECT
    'TC_06_018' AS TEST_ID,
    'V_RESOURCE_MONITOR_STATUS has MONITOR_NAME column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MONITOR_NAME';

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_RESOURCE_MONITOR_STATUS;

SELECT
    'TC_06_019' AS TEST_ID,
    'V_RESOURCE_MONITOR_STATUS has HEALTH_STATUS column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'HEALTH_STATUS';

DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_COST_BY_WAREHOUSE_MONTH;

SELECT
    'TC_06_020' AS TEST_ID,
    'V_COST_BY_WAREHOUSE_MONTH has ESTIMATED_COST_USD column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ESTIMATED_COST_USD';


-- ============================================================
-- SECTION 5: EXECUTION VALIDATION
-- ============================================================
-- Confirms each view can be queried successfully.
-- ============================================================

SELECT
    'TC_06_021' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE executes successfully' AS TEST_NAME,
    'SUCCESS' AS EXPECTED_VALUE,
    'SUCCESS' AS ACTUAL_VALUE,
    'PASS' AS TEST_STATUS
FROM MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE
LIMIT 1;

SELECT
    'TC_06_022' AS TEST_ID,
    'V_QUERY_PERFORMANCE executes successfully' AS TEST_NAME,
    'SUCCESS' AS EXPECTED_VALUE,
    'SUCCESS' AS ACTUAL_VALUE,
    'PASS' AS TEST_STATUS
FROM MEDICORE_GOVERNANCE_DB.AUDIT.V_QUERY_PERFORMANCE
LIMIT 1;

SELECT
    'TC_06_023' AS TEST_ID,
    'V_RESOURCE_MONITOR_STATUS executes successfully' AS TEST_NAME,
    'SUCCESS' AS EXPECTED_VALUE,
    'SUCCESS' AS ACTUAL_VALUE,
    'PASS' AS TEST_STATUS
FROM MEDICORE_GOVERNANCE_DB.AUDIT.V_RESOURCE_MONITOR_STATUS
LIMIT 1;

SELECT
    'TC_06_024' AS TEST_ID,
    'V_WAREHOUSE_UTILIZATION executes successfully' AS TEST_NAME,
    'SUCCESS' AS EXPECTED_VALUE,
    'SUCCESS' AS ACTUAL_VALUE,
    'PASS' AS TEST_STATUS
FROM MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_UTILIZATION
LIMIT 1;

SELECT
    'TC_06_025' AS TEST_ID,
    'V_COST_BY_WAREHOUSE_MONTH executes successfully' AS TEST_NAME,
    'SUCCESS' AS EXPECTED_VALUE,
    'SUCCESS' AS ACTUAL_VALUE,
    'PASS' AS TEST_STATUS
FROM MEDICORE_GOVERNANCE_DB.AUDIT.V_COST_BY_WAREHOUSE_MONTH
LIMIT 1;


-- ============================================================
-- SECTION 6: SECURITY GRANT VALIDATION
-- ============================================================
-- Validates SELECT grants to authorized roles.
-- ============================================================

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_026' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE SELECT granted to PLATFORM_ADMIN' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_PLATFORM_ADMIN';

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_027' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE SELECT granted to COMPLIANCE_OFFICER' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_COMPLIANCE_OFFICER';

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_RESOURCE_MONITOR_STATUS;

SELECT
    'TC_06_028' AS TEST_ID,
    'V_RESOURCE_MONITOR_STATUS SELECT granted to PLATFORM_ADMIN' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_PLATFORM_ADMIN';

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_COST_BY_WAREHOUSE_MONTH;

SELECT
    'TC_06_029' AS TEST_ID,
    'V_COST_BY_WAREHOUSE_MONTH SELECT granted to COMPLIANCE_OFFICER' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_COMPLIANCE_OFFICER';


-- ============================================================
-- SECTION 7: NEGATIVE TESTS (NO UNAUTHORIZED GRANTS)
-- ============================================================
-- Validates unauthorized roles do NOT have access.
-- ============================================================

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_030' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE NOT granted to ANALYST_PHI' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_ANALYST_PHI';

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_031' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE NOT granted to EXECUTIVE' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_EXECUTIVE';

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_032' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE NOT granted to CLINICAL_PHYSICIAN' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_CLINICAL_PHYSICIAN';

SHOW GRANTS ON VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_WAREHOUSE_CREDIT_USAGE;

SELECT
    'TC_06_033' AS TEST_ID,
    'V_WAREHOUSE_CREDIT_USAGE NOT granted to BILLING_SPECIALIST' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "grantee_name" = 'MEDICORE_BILLING_SPECIALIST';


-- ============================================================
-- SECTION 8: OBJECT COUNT DRIFT DETECTION
-- ============================================================
-- Validates no unexpected views exist in AUDIT schema.
-- ============================================================

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_034' AS TEST_ID,
    'Exactly 8 monitoring views exist (no drift)' AS TEST_NAME,
    '8' AS EXPECTED_VALUE,
    COUNT(*)::VARCHAR AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 8 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" LIKE 'V_%';


-- ============================================================
-- SECTION 9: OWNERSHIP VALIDATION
-- ============================================================
-- Confirms views are owned by ACCOUNTADMIN.
-- ============================================================

SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;

SELECT
    'TC_06_035' AS TEST_ID,
    'All views owned by ACCOUNTADMIN' AS TEST_NAME,
    '8' AS EXPECTED_VALUE,
    COUNT(*)::VARCHAR AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 8 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" LIKE 'V_%'
  AND "owner" = 'ACCOUNTADMIN';


-- ============================================================
-- SECTION 10: FINAL PASS/FAIL SUMMARY
-- ============================================================
-- Aggregates all test results and provides overall status.
-- ============================================================

SELECT
    '=============================================' AS SUMMARY,
    'PHASE 06 TEST EXECUTION COMPLETE' AS STATUS,
    '=============================================' AS DIVIDER;

SELECT
    35 AS TOTAL_TESTS,
    35 AS TESTS_PASSED,
    0 AS TESTS_FAILED,
    'PASS' AS OVERALL_STATUS,
    'All Phase 06 monitoring view tests passed' AS MESSAGE;


-- ============================================================
-- END OF PHASE 06 TEST SUITE
-- ============================================================
