-- ============================================================
-- MEDICORE HEALTH SYSTEMS — PHASE 08 TEST SUITE
-- DATA GOVERNANCE VALIDATION
-- ============================================================
-- Script:      08_test_data_governance.sql
-- Version:     1.0.0
-- Purpose:     Validate Phase 08 data governance implementation
--
-- SAFETY DECLARATION:
-- -------------------
-- This script is READ-ONLY and NON-DESTRUCTIVE.
-- Safe for production execution.
-- Designed for CI/CD pipeline integration.
-- Does not create, modify, or delete any objects.
-- Does not apply tags or bind policies.
--
-- VALIDATION SCOPE:
-- -----------------
-- - 13 TAG objects in MEDICORE_GOVERNANCE_DB.TAGS
-- - 7 MASKING POLICIES in MEDICORE_GOVERNANCE_DB.POLICIES
-- - 4 ROW ACCESS POLICIES in MEDICORE_GOVERNANCE_DB.POLICIES
-- - Governance grants to MEDICORE_COMPLIANCE_OFFICER
-- - Ownership validation (ACCOUNTADMIN)
-- - Drift detection (object counts)
-- - Negative tests (unauthorized privileges)
--
-- GOVERNANCE CONTEXT:
-- -------------------
-- Phase 08 implements HIPAA and 42 CFR Part 2 compliant
-- data governance including:
--   - PHI classification tags
--   - Dynamic data masking policies
--   - Row-level access policies
--   - Consent-based access framework
--
-- Execution: Run as ACCOUNTADMIN
-- ============================================================

-- ============================================================
-- ENVIRONMENT SETUP
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- SECTION 1: TAG EXISTENCE VALIDATION
-- ============================================================
-- Validates all 13 required TAG objects exist in the
-- MEDICORE_GOVERNANCE_DB.TAGS schema.
-- ============================================================

-- Get all tags in TAGS schema
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;

-- TC_08_001: PHI_CLASSIFICATION tag exists
SELECT
    'TC_08_001' AS TEST_ID,
    'PHI_CLASSIFICATION tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'PHI_CLASSIFICATION';

-- TC_08_002: PHI_ELEMENT_TYPE tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_002' AS TEST_ID,
    'PHI_ELEMENT_TYPE tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'PHI_ELEMENT_TYPE';

-- TC_08_003: DATA_DOMAIN tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_003' AS TEST_ID,
    'DATA_DOMAIN tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'DATA_DOMAIN';

-- TC_08_004: DATA_SUBDOMAIN tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_004' AS TEST_ID,
    'DATA_SUBDOMAIN tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'DATA_SUBDOMAIN';

-- TC_08_005: DATA_QUALITY_STATUS tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_005' AS TEST_ID,
    'DATA_QUALITY_STATUS tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'DATA_QUALITY_STATUS';

-- TC_08_006: DQ_ISSUE_TYPE tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_006' AS TEST_ID,
    'DQ_ISSUE_TYPE tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'DQ_ISSUE_TYPE';

-- TC_08_007: MEDALLION_LAYER tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_007' AS TEST_ID,
    'MEDALLION_LAYER tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MEDALLION_LAYER';

-- TC_08_008: ENVIRONMENT tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_008' AS TEST_ID,
    'ENVIRONMENT tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ENVIRONMENT';

-- TC_08_009: SOURCE_SYSTEM tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_009' AS TEST_ID,
    'SOURCE_SYSTEM tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'SOURCE_SYSTEM';

-- TC_08_010: REFRESH_FREQUENCY tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_010' AS TEST_ID,
    'REFRESH_FREQUENCY tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'REFRESH_FREQUENCY';

-- TC_08_011: REGULATORY_FRAMEWORK tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_011' AS TEST_ID,
    'REGULATORY_FRAMEWORK tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'REGULATORY_FRAMEWORK';

-- TC_08_012: CONSENT_REQUIRED tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_012' AS TEST_ID,
    'CONSENT_REQUIRED tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'CONSENT_REQUIRED';

-- TC_08_013: RETENTION_POLICY tag exists
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_013' AS TEST_ID,
    'RETENTION_POLICY tag exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'RETENTION_POLICY';


-- ============================================================
-- SECTION 2: MASKING POLICY VALIDATION
-- ============================================================
-- Validates all 7 required MASKING POLICY objects exist in
-- MEDICORE_GOVERNANCE_DB.POLICIES schema with correct return types.
-- ============================================================

-- Get all masking policies in POLICIES schema
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;

-- TC_08_014: MASK_DIRECT_IDENTIFIER policy exists
SELECT
    'TC_08_014' AS TEST_ID,
    'MASK_DIRECT_IDENTIFIER policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_DIRECT_IDENTIFIER';

-- TC_08_015: MASK_QUASI_IDENTIFIER policy exists
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_015' AS TEST_ID,
    'MASK_QUASI_IDENTIFIER policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_QUASI_IDENTIFIER';

-- TC_08_016: MASK_QUASI_IDENTIFIER_DATE policy exists
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_016' AS TEST_ID,
    'MASK_QUASI_IDENTIFIER_DATE policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_QUASI_IDENTIFIER_DATE';

-- TC_08_017: MASK_QUASI_IDENTIFIER_TIMESTAMP policy exists
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_017' AS TEST_ID,
    'MASK_QUASI_IDENTIFIER_TIMESTAMP policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_QUASI_IDENTIFIER_TIMESTAMP';

-- TC_08_018: MASK_SENSITIVE_CLINICAL policy exists
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_018' AS TEST_ID,
    'MASK_SENSITIVE_CLINICAL policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_SENSITIVE_CLINICAL';

-- TC_08_019: MASK_42CFR_PART2 policy exists
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_019' AS TEST_ID,
    'MASK_42CFR_PART2 policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_42CFR_PART2';

-- TC_08_020: MASK_FINANCIAL_PII policy exists
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_020' AS TEST_ID,
    'MASK_FINANCIAL_PII policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_FINANCIAL_PII';

-- TC_08_021: MASK_DIRECT_IDENTIFIER returns STRING
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_021' AS TEST_ID,
    'MASK_DIRECT_IDENTIFIER returns STRING' AS TEST_NAME,
    'VARCHAR' AS EXPECTED_VALUE,
    COALESCE(MAX("return_type"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("return_type") LIKE '%VARCHAR%' OR MAX("return_type") LIKE '%STRING%' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_DIRECT_IDENTIFIER';

-- TC_08_022: MASK_QUASI_IDENTIFIER_DATE returns DATE
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_022' AS TEST_ID,
    'MASK_QUASI_IDENTIFIER_DATE returns DATE' AS TEST_NAME,
    'DATE' AS EXPECTED_VALUE,
    COALESCE(MAX("return_type"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("return_type") LIKE '%DATE%' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_QUASI_IDENTIFIER_DATE';

-- TC_08_023: MASK_QUASI_IDENTIFIER_TIMESTAMP returns TIMESTAMP
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_023' AS TEST_ID,
    'MASK_QUASI_IDENTIFIER_TIMESTAMP returns TIMESTAMP' AS TEST_NAME,
    'TIMESTAMP_NTZ' AS EXPECTED_VALUE,
    COALESCE(MAX("return_type"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("return_type") LIKE '%TIMESTAMP%' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'MASK_QUASI_IDENTIFIER_TIMESTAMP';


-- ============================================================
-- SECTION 3: ROW ACCESS POLICY VALIDATION
-- ============================================================
-- Validates all 4 required ROW ACCESS POLICY objects exist in
-- MEDICORE_GOVERNANCE_DB.POLICIES schema with BOOLEAN return type.
-- ============================================================

-- Get all row access policies in POLICIES schema
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;

-- TC_08_024: ROW_ACCESS_CLINICAL policy exists
SELECT
    'TC_08_024' AS TEST_ID,
    'ROW_ACCESS_CLINICAL policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_CLINICAL';

-- TC_08_025: ROW_ACCESS_ENVIRONMENT policy exists
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_025' AS TEST_ID,
    'ROW_ACCESS_ENVIRONMENT policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_ENVIRONMENT';

-- TC_08_026: ROW_ACCESS_CONSENT policy exists
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_026' AS TEST_ID,
    'ROW_ACCESS_CONSENT policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_CONSENT';

-- TC_08_027: ROW_ACCESS_DATA_QUALITY policy exists
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_027' AS TEST_ID,
    'ROW_ACCESS_DATA_QUALITY policy exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_DATA_QUALITY';

-- TC_08_028: ROW_ACCESS_CLINICAL returns BOOLEAN
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_028' AS TEST_ID,
    'ROW_ACCESS_CLINICAL returns BOOLEAN' AS TEST_NAME,
    'BOOLEAN' AS EXPECTED_VALUE,
    COALESCE(MAX("return_type"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("return_type") = 'BOOLEAN' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_CLINICAL';

-- TC_08_029: ROW_ACCESS_ENVIRONMENT returns BOOLEAN
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_029' AS TEST_ID,
    'ROW_ACCESS_ENVIRONMENT returns BOOLEAN' AS TEST_NAME,
    'BOOLEAN' AS EXPECTED_VALUE,
    COALESCE(MAX("return_type"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("return_type") = 'BOOLEAN' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_ENVIRONMENT';

-- TC_08_029a: ROW_ACCESS_CONSENT returns BOOLEAN
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_029a' AS TEST_ID,
    'ROW_ACCESS_CONSENT returns BOOLEAN' AS TEST_NAME,
    'BOOLEAN' AS EXPECTED_VALUE,
    COALESCE(MAX("return_type"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("return_type") = 'BOOLEAN' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_CONSENT';

-- TC_08_029b: ROW_ACCESS_DATA_QUALITY returns BOOLEAN
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_029b' AS TEST_ID,
    'ROW_ACCESS_DATA_QUALITY returns BOOLEAN' AS TEST_NAME,
    'BOOLEAN' AS EXPECTED_VALUE,
    COALESCE(MAX("return_type"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("return_type") = 'BOOLEAN' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'ROW_ACCESS_DATA_QUALITY';


-- ============================================================
-- SECTION 4: SCHEMA PLACEMENT VALIDATION
-- ============================================================
-- Validates governance objects are in correct schemas.
-- ============================================================

-- TC_08_030: Tags are in MEDICORE_GOVERNANCE_DB.TAGS schema
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_030' AS TEST_ID,
    'All tags in MEDICORE_GOVERNANCE_DB.TAGS' AS TEST_NAME,
    'MEDICORE_GOVERNANCE_DB.TAGS' AS EXPECTED_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND COUNT(DISTINCT "database_name" || '.' || "schema_name") = 1 
             AND MAX("database_name") = 'MEDICORE_GOVERNANCE_DB' 
             AND MAX("schema_name") = 'TAGS'
        THEN 'MEDICORE_GOVERNANCE_DB.TAGS' 
        ELSE 'INCORRECT_SCHEMA' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND MAX("database_name") = 'MEDICORE_GOVERNANCE_DB' AND MAX("schema_name") = 'TAGS'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_031: Masking policies are in MEDICORE_GOVERNANCE_DB.POLICIES schema
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_031' AS TEST_ID,
    'All masking policies in MEDICORE_GOVERNANCE_DB.POLICIES' AS TEST_NAME,
    'MEDICORE_GOVERNANCE_DB.POLICIES' AS EXPECTED_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND MAX("database_name") = 'MEDICORE_GOVERNANCE_DB' AND MAX("schema_name") = 'POLICIES'
        THEN 'MEDICORE_GOVERNANCE_DB.POLICIES' 
        ELSE 'INCORRECT_SCHEMA' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND MAX("database_name") = 'MEDICORE_GOVERNANCE_DB' AND MAX("schema_name") = 'POLICIES'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_032: Row access policies are in MEDICORE_GOVERNANCE_DB.POLICIES schema
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_032' AS TEST_ID,
    'All row access policies in MEDICORE_GOVERNANCE_DB.POLICIES' AS TEST_NAME,
    'MEDICORE_GOVERNANCE_DB.POLICIES' AS EXPECTED_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND MAX("database_name") = 'MEDICORE_GOVERNANCE_DB' AND MAX("schema_name") = 'POLICIES'
        THEN 'MEDICORE_GOVERNANCE_DB.POLICIES' 
        ELSE 'INCORRECT_SCHEMA' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND MAX("database_name") = 'MEDICORE_GOVERNANCE_DB' AND MAX("schema_name") = 'POLICIES'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));


-- ============================================================
-- SECTION 5: OWNERSHIP VALIDATION
-- ============================================================
-- Validates all governance objects are owned by ACCOUNTADMIN.
-- ============================================================

-- TC_08_033: All tags owned by ACCOUNTADMIN
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_033' AS TEST_ID,
    'All tags owned by ACCOUNTADMIN' AS TEST_NAME,
    'ACCOUNTADMIN' AS EXPECTED_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND COUNT(DISTINCT "owner") = 1 AND MAX("owner") = 'ACCOUNTADMIN'
        THEN 'ACCOUNTADMIN' 
        ELSE COALESCE(LISTAGG(DISTINCT "owner", ', '), 'NO_TAGS') 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND COUNT(DISTINCT "owner") = 1 AND MAX("owner") = 'ACCOUNTADMIN'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_034: All masking policies owned by ACCOUNTADMIN
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_034' AS TEST_ID,
    'All masking policies owned by ACCOUNTADMIN' AS TEST_NAME,
    'ACCOUNTADMIN' AS EXPECTED_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND COUNT(DISTINCT "owner") = 1 AND MAX("owner") = 'ACCOUNTADMIN'
        THEN 'ACCOUNTADMIN' 
        ELSE COALESCE(LISTAGG(DISTINCT "owner", ', '), 'NO_POLICIES') 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND COUNT(DISTINCT "owner") = 1 AND MAX("owner") = 'ACCOUNTADMIN'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_035: All row access policies owned by ACCOUNTADMIN
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_035' AS TEST_ID,
    'All row access policies owned by ACCOUNTADMIN' AS TEST_NAME,
    'ACCOUNTADMIN' AS EXPECTED_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND COUNT(DISTINCT "owner") = 1 AND MAX("owner") = 'ACCOUNTADMIN'
        THEN 'ACCOUNTADMIN' 
        ELSE COALESCE(LISTAGG(DISTINCT "owner", ', '), 'NO_POLICIES') 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN COUNT(*) > 0 AND COUNT(DISTINCT "owner") = 1 AND MAX("owner") = 'ACCOUNTADMIN'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_036: TAGS schema owned by ACCOUNTADMIN
SHOW SCHEMAS IN DATABASE MEDICORE_GOVERNANCE_DB;
SELECT
    'TC_08_036' AS TEST_ID,
    'TAGS schema owned by ACCOUNTADMIN' AS TEST_NAME,
    'ACCOUNTADMIN' AS EXPECTED_VALUE,
    COALESCE(MAX("owner"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("owner") = 'ACCOUNTADMIN' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'TAGS';

-- TC_08_037: POLICIES schema owned by ACCOUNTADMIN
SHOW SCHEMAS IN DATABASE MEDICORE_GOVERNANCE_DB;
SELECT
    'TC_08_037' AS TEST_ID,
    'POLICIES schema owned by ACCOUNTADMIN' AS TEST_NAME,
    'ACCOUNTADMIN' AS EXPECTED_VALUE,
    COALESCE(MAX("owner"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("owner") = 'ACCOUNTADMIN' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'POLICIES';


-- ============================================================
-- SECTION 6: PRIVILEGE VALIDATION
-- ============================================================
-- Validates MEDICORE_COMPLIANCE_OFFICER has required governance
-- privileges for managing tags and policies.
-- ============================================================

-- TC_08_038: COMPLIANCE_OFFICER has CREATE TAG on TAGS schema
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_038' AS TEST_ID,
    'COMPLIANCE_OFFICER has CREATE TAG on TAGS schema' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE TAG'
  AND "granted_on" = 'SCHEMA'
  AND "name" LIKE '%TAGS%';

-- TC_08_039: COMPLIANCE_OFFICER has CREATE MASKING POLICY on POLICIES schema
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_039' AS TEST_ID,
    'COMPLIANCE_OFFICER has CREATE MASKING POLICY on POLICIES schema' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE MASKING POLICY'
  AND "granted_on" = 'SCHEMA'
  AND "name" LIKE '%POLICIES%';

-- TC_08_040: COMPLIANCE_OFFICER has CREATE ROW ACCESS POLICY on POLICIES schema
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_040' AS TEST_ID,
    'COMPLIANCE_OFFICER has CREATE ROW ACCESS POLICY on POLICIES schema' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE ROW ACCESS POLICY'
  AND "granted_on" = 'SCHEMA'
  AND "name" LIKE '%POLICIES%';

-- TC_08_041: COMPLIANCE_OFFICER has APPLY TAG on ACCOUNT
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_041' AS TEST_ID,
    'COMPLIANCE_OFFICER has APPLY TAG on ACCOUNT' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'APPLY TAG'
  AND "granted_on" = 'ACCOUNT';

-- TC_08_042: COMPLIANCE_OFFICER has APPLY MASKING POLICY on ACCOUNT
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_042' AS TEST_ID,
    'COMPLIANCE_OFFICER has APPLY MASKING POLICY on ACCOUNT' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'APPLY MASKING POLICY'
  AND "granted_on" = 'ACCOUNT';

-- TC_08_043: COMPLIANCE_OFFICER has APPLY ROW ACCESS POLICY on ACCOUNT
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_043' AS TEST_ID,
    'COMPLIANCE_OFFICER has APPLY ROW ACCESS POLICY on ACCOUNT' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'APPLY ROW ACCESS POLICY'
  AND "granted_on" = 'ACCOUNT';

-- TC_08_044: COMPLIANCE_OFFICER has USAGE on TAGS schema
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_044' AS TEST_ID,
    'COMPLIANCE_OFFICER has USAGE on TAGS schema' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'USAGE'
  AND "granted_on" = 'SCHEMA'
  AND "name" LIKE '%TAGS%';

-- TC_08_045: COMPLIANCE_OFFICER has USAGE on POLICIES schema
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_08_045' AS TEST_ID,
    'COMPLIANCE_OFFICER has USAGE on POLICIES schema' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'USAGE'
  AND "granted_on" = 'SCHEMA'
  AND "name" LIKE '%POLICIES%';


-- ============================================================
-- SECTION 7: NEGATIVE TESTS (UNAUTHORIZED PRIVILEGES)
-- ============================================================
-- Validates that unauthorized roles do NOT have governance
-- creation privileges. This enforces separation of duties.
-- ============================================================

-- TC_08_046: DATA_ENGINEER does NOT have CREATE TAG privilege
SHOW GRANTS TO ROLE MEDICORE_DATA_ENGINEER;
SELECT
    'TC_08_046' AS TEST_ID,
    'DATA_ENGINEER does NOT have CREATE TAG' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE TAG';

-- TC_08_047: DATA_ENGINEER does NOT have CREATE MASKING POLICY privilege
SHOW GRANTS TO ROLE MEDICORE_DATA_ENGINEER;
SELECT
    'TC_08_047' AS TEST_ID,
    'DATA_ENGINEER does NOT have CREATE MASKING POLICY' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE MASKING POLICY';

-- TC_08_048: ANALYST_PHI does NOT have CREATE TAG privilege
SHOW GRANTS TO ROLE MEDICORE_ANALYST_PHI;
SELECT
    'TC_08_048' AS TEST_ID,
    'ANALYST_PHI does NOT have CREATE TAG' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE TAG';

-- TC_08_049: CLINICAL_PHYSICIAN does NOT have CREATE MASKING POLICY privilege
SHOW GRANTS TO ROLE MEDICORE_CLINICAL_PHYSICIAN;
SELECT
    'TC_08_049' AS TEST_ID,
    'CLINICAL_PHYSICIAN does NOT have CREATE MASKING POLICY' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE MASKING POLICY';

-- TC_08_050: BILLING_SPECIALIST does NOT have CREATE ROW ACCESS POLICY privilege
SHOW GRANTS TO ROLE MEDICORE_BILLING_SPECIALIST;
SELECT
    'TC_08_050' AS TEST_ID,
    'BILLING_SPECIALIST does NOT have CREATE ROW ACCESS POLICY' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE ROW ACCESS POLICY';

-- TC_08_051: EXECUTIVE does NOT have APPLY TAG privilege
SHOW GRANTS TO ROLE MEDICORE_EXECUTIVE;
SELECT
    'TC_08_051' AS TEST_ID,
    'EXECUTIVE does NOT have APPLY TAG' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'APPLY TAG';


-- ============================================================
-- SECTION 8: DRIFT DETECTION (OBJECT COUNT)
-- ============================================================
-- Validates exact counts of governance objects to detect
-- configuration drift (missing or unexpected objects).
-- ============================================================

-- TC_08_052: Tag count equals 13
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT
    'TC_08_052' AS TEST_ID,
    'Tag count equals 13' AS TEST_NAME,
    '13' AS EXPECTED_VALUE,
    COUNT(*)::STRING AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 13 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_053: Masking policy count equals 7
SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_053' AS TEST_ID,
    'Masking policy count equals 7' AS TEST_NAME,
    '7' AS EXPECTED_VALUE,
    COUNT(*)::STRING AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 7 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_054: Row access policy count equals 4
SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT
    'TC_08_054' AS TEST_ID,
    'Row access policy count equals 4' AS TEST_NAME,
    '4' AS EXPECTED_VALUE,
    COUNT(*)::STRING AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 4 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));


-- ============================================================
-- SECTION 8a: POLICY STRUCTURE VALIDATION
-- ============================================================
-- Validates policy definitions contain required logic patterns
-- using GET_DDL for read-only inspection.
-- ============================================================

-- TC_08_054a: MASK_DIRECT_IDENTIFIER contains CURRENT_ROLE() logic
SELECT
    'TC_08_054a' AS TEST_ID,
    'MASK_DIRECT_IDENTIFIER contains CURRENT_ROLE()' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.MASK_DIRECT_IDENTIFIER') LIKE '%CURRENT_ROLE()%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.MASK_DIRECT_IDENTIFIER') LIKE '%CURRENT_ROLE()%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_08_054b: MASK_DIRECT_IDENTIFIER contains CASE expression
SELECT
    'TC_08_054b' AS TEST_ID,
    'MASK_DIRECT_IDENTIFIER contains CASE expression' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.MASK_DIRECT_IDENTIFIER') LIKE '%CASE%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.MASK_DIRECT_IDENTIFIER') LIKE '%CASE%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_08_054c: MASK_42CFR_PART2 contains COMPLIANCE_OFFICER role check
SELECT
    'TC_08_054c' AS TEST_ID,
    'MASK_42CFR_PART2 contains COMPLIANCE_OFFICER check' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.MASK_42CFR_PART2') LIKE '%MEDICORE_COMPLIANCE_OFFICER%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.MASK_42CFR_PART2') LIKE '%MEDICORE_COMPLIANCE_OFFICER%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_08_054d: ROW_ACCESS_CLINICAL contains CURRENT_ROLE() logic
SELECT
    'TC_08_054d' AS TEST_ID,
    'ROW_ACCESS_CLINICAL contains CURRENT_ROLE()' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.ROW_ACCESS_CLINICAL') LIKE '%CURRENT_ROLE()%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.ROW_ACCESS_CLINICAL') LIKE '%CURRENT_ROLE()%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_08_054e: ROW_ACCESS_CLINICAL contains SUBSTANCE_ABUSE handling
SELECT
    'TC_08_054e' AS TEST_ID,
    'ROW_ACCESS_CLINICAL handles SUBSTANCE_ABUSE' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.ROW_ACCESS_CLINICAL') LIKE '%SUBSTANCE_ABUSE%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.ROW_ACCESS_CLINICAL') LIKE '%SUBSTANCE_ABUSE%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_08_054f: ROW_ACCESS_ENVIRONMENT contains environment check
SELECT
    'TC_08_054f' AS TEST_ID,
    'ROW_ACCESS_ENVIRONMENT contains PROD/QA/DEV check' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.ROW_ACCESS_ENVIRONMENT') LIKE '%PROD%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('POLICY', 'MEDICORE_GOVERNANCE_DB.POLICIES.ROW_ACCESS_ENVIRONMENT') LIKE '%PROD%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;


-- ============================================================
-- SECTION 9: GOVERNANCE SCHEMA SECURITY VALIDATION
-- ============================================================
-- Validates governance schemas are not owned by non-admin roles
-- and have appropriate security configurations.
-- ============================================================

-- TC_08_055: TAGS schema not owned by DATA_ENGINEER
SHOW SCHEMAS IN DATABASE MEDICORE_GOVERNANCE_DB;
SELECT
    'TC_08_055' AS TEST_ID,
    'TAGS schema not owned by DATA_ENGINEER' AS TEST_NAME,
    'NOT_OWNER' AS EXPECTED_VALUE,
    CASE WHEN MAX("owner") != 'MEDICORE_DATA_ENGINEER' THEN 'NOT_OWNER' ELSE 'IS_OWNER' END AS ACTUAL_VALUE,
    CASE WHEN MAX("owner") != 'MEDICORE_DATA_ENGINEER' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'TAGS';

-- TC_08_056: POLICIES schema not owned by DATA_ENGINEER
SHOW SCHEMAS IN DATABASE MEDICORE_GOVERNANCE_DB;
SELECT
    'TC_08_056' AS TEST_ID,
    'POLICIES schema not owned by DATA_ENGINEER' AS TEST_NAME,
    'NOT_OWNER' AS EXPECTED_VALUE,
    CASE WHEN MAX("owner") != 'MEDICORE_DATA_ENGINEER' THEN 'NOT_OWNER' ELSE 'IS_OWNER' END AS ACTUAL_VALUE,
    CASE WHEN MAX("owner") != 'MEDICORE_DATA_ENGINEER' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'POLICIES';

-- TC_08_057: MEDICORE_GOVERNANCE_DB exists
SHOW DATABASES LIKE 'MEDICORE_GOVERNANCE_DB';
SELECT
    'TC_08_057' AS TEST_ID,
    'MEDICORE_GOVERNANCE_DB exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_08_058: MEDICORE_GOVERNANCE_DB owned by ACCOUNTADMIN
SHOW DATABASES LIKE 'MEDICORE_GOVERNANCE_DB';
SELECT
    'TC_08_058' AS TEST_ID,
    'MEDICORE_GOVERNANCE_DB owned by ACCOUNTADMIN' AS TEST_NAME,
    'ACCOUNTADMIN' AS EXPECTED_VALUE,
    COALESCE(MAX("owner"), 'NOT_FOUND') AS ACTUAL_VALUE,
    CASE WHEN MAX("owner") = 'ACCOUNTADMIN' THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));


-- ============================================================
-- SECTION 10: FINAL PASS/FAIL SUMMARY
-- ============================================================
-- Aggregates all test results into a final summary.
-- ============================================================

SELECT
    '=============================================' AS SEPARATOR;

SELECT
    'PHASE 08 DATA GOVERNANCE TEST SUMMARY' AS REPORT_TITLE,
    CURRENT_TIMESTAMP() AS EXECUTION_TIME,
    CURRENT_ROLE() AS EXECUTED_BY;

SELECT
    '=============================================' AS SEPARATOR;

SELECT
    'TOTAL_TESTS: 67' AS METRIC,
    'See individual test results above for details' AS NOTE;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '13 Tag Existence Tests (TC_08_001 - TC_08_013)' AS SECTION_1;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '10 Masking Policy Tests (TC_08_014 - TC_08_023)' AS SECTION_2;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '8 Row Access Policy Tests (TC_08_024 - TC_08_029b)' AS SECTION_3;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '3 Schema Placement Tests (TC_08_030 - TC_08_032)' AS SECTION_4;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '5 Ownership Tests (TC_08_033 - TC_08_037)' AS SECTION_5;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '8 Privilege Tests (TC_08_038 - TC_08_045)' AS SECTION_6;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '6 Negative Tests (TC_08_046 - TC_08_051)' AS SECTION_7;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '3 Drift Detection Tests (TC_08_052 - TC_08_054)' AS SECTION_8;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '6 Policy Structure Tests (TC_08_054a - TC_08_054f)' AS SECTION_8a;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '4 Schema Security Tests (TC_08_055 - TC_08_058)' AS SECTION_9;

SELECT
    '=============================================' AS SEPARATOR;

SELECT
    'GOVERNANCE OBJECTS SUMMARY' AS REPORT_SECTION;

-- Summary of governance objects
SHOW TAGS IN SCHEMA MEDICORE_GOVERNANCE_DB.TAGS;
SELECT 'TAGS' AS OBJECT_TYPE, COUNT(*) AS COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW MASKING POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT 'MASKING_POLICIES' AS OBJECT_TYPE, COUNT(*) AS COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW ROW ACCESS POLICIES IN SCHEMA MEDICORE_GOVERNANCE_DB.POLICIES;
SELECT 'ROW_ACCESS_POLICIES' AS OBJECT_TYPE, COUNT(*) AS COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT
    '=============================================' AS SEPARATOR;

SELECT
    'END OF PHASE 08 GOVERNANCE TEST SUITE' AS STATUS,
    'Review individual test results for PASS/FAIL status' AS ACTION;


-- ============================================================
-- END OF TEST SUITE
-- ============================================================
