-- ============================================================
-- MEDICORE HEALTH SYSTEMS — PHASE 09 AUDIT VALIDATION SUITE
-- ============================================================
-- Script:      09_test_audit.sql
-- Version:     1.0.0
-- Environment: Enterprise Snowflake (HIPAA-regulated)
-- Purpose:     Validate Phase 09 Audit & Compliance Framework
--
-- VALIDATION SCOPE:
-- -----------------
-- This test suite validates:
--   - 13 audit views exist in MEDICORE_GOVERNANCE_DB.AUDIT
--   - View structure and column validation
--   - Data latency safety (time filters present)
--   - Security grants (COMPLIANCE_OFFICER, PLATFORM_ADMIN)
--   - Sensitive view filters (PHI, 42CFR)
--   - Risk scoring logic validation
--   - Drift detection
--
-- TEST CHARACTERISTICS:
-- ---------------------
--   - Production-safe (read-only)
--   - CI/CD compatible
--   - Idempotent
--   - Non-destructive
--   - HIPAA audit readiness validation
--
-- Prerequisites:
--   - Phase 09 deployed
--   - ACCOUNTADMIN role
--
-- Execution: Run as ACCOUNTADMIN
-- ============================================================


-- ============================================================
-- ENVIRONMENT SETUP
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE MEDICORE_GOVERNANCE_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA AUDIT;


-- ============================================================
-- SECTION 1: VIEW EXISTENCE VALIDATION
-- ============================================================
-- Validates that all 13 expected audit views exist with
-- correct ownership in MEDICORE_GOVERNANCE_DB.AUDIT.
-- ============================================================

-- TC_09_001: V_LOGIN_HISTORY exists
SHOW VIEWS LIKE 'V_LOGIN_HISTORY' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_001' AS TEST_ID,
    'V_LOGIN_HISTORY exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_002: V_ROLE_GRANT_HISTORY exists
SHOW VIEWS LIKE 'V_ROLE_GRANT_HISTORY' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_002' AS TEST_ID,
    'V_ROLE_GRANT_HISTORY exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_003: V_PRIVILEGE_ESCALATION_EVENTS exists
SHOW VIEWS LIKE 'V_PRIVILEGE_ESCALATION_EVENTS' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_003' AS TEST_ID,
    'V_PRIVILEGE_ESCALATION_EVENTS exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_004: V_PHI_DATA_ACCESS exists
SHOW VIEWS LIKE 'V_PHI_DATA_ACCESS' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_004' AS TEST_ID,
    'V_PHI_DATA_ACCESS exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_005: V_MASKING_POLICY_USAGE exists
SHOW VIEWS LIKE 'V_MASKING_POLICY_USAGE' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_005' AS TEST_ID,
    'V_MASKING_POLICY_USAGE exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_006: V_ROW_ACCESS_POLICY_USAGE exists
SHOW VIEWS LIKE 'V_ROW_ACCESS_POLICY_USAGE' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_006' AS TEST_ID,
    'V_ROW_ACCESS_POLICY_USAGE exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_007: V_TAG_CHANGE_HISTORY exists
SHOW VIEWS LIKE 'V_TAG_CHANGE_HISTORY' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_007' AS TEST_ID,
    'V_TAG_CHANGE_HISTORY exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_008: V_POLICY_CHANGE_HISTORY exists
SHOW VIEWS LIKE 'V_POLICY_CHANGE_HISTORY' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_008' AS TEST_ID,
    'V_POLICY_CHANGE_HISTORY exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_009: V_QUARANTINED_DATA_ACCESS_ATTEMPTS exists
SHOW VIEWS LIKE 'V_QUARANTINED_DATA_ACCESS_ATTEMPTS' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_009' AS TEST_ID,
    'V_QUARANTINED_DATA_ACCESS_ATTEMPTS exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_010: V_42CFR_ACCESS_ATTEMPTS exists
SHOW VIEWS LIKE 'V_42CFR_ACCESS_ATTEMPTS' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_010' AS TEST_ID,
    'V_42CFR_ACCESS_ATTEMPTS exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_011: V_SESSION_HISTORY exists
SHOW VIEWS LIKE 'V_SESSION_HISTORY' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_011' AS TEST_ID,
    'V_SESSION_HISTORY exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_012: V_ADMIN_ACTIVITY exists
SHOW VIEWS LIKE 'V_ADMIN_ACTIVITY' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_012' AS TEST_ID,
    'V_ADMIN_ACTIVITY exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- TC_09_013: V_SECURITY_RISK_SCORE exists
SHOW VIEWS LIKE 'V_SECURITY_RISK_SCORE' IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_013' AS TEST_ID,
    'V_SECURITY_RISK_SCORE exists' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));


-- ============================================================
-- SECTION 2: VIEW OWNERSHIP VALIDATION
-- ============================================================
-- Validates all audit views owned by ACCOUNTADMIN.
-- ============================================================

-- TC_09_014: All Phase 09 audit views owned by ACCOUNTADMIN
SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_014' AS TEST_ID,
    'All Phase 09 views owned by ACCOUNTADMIN' AS TEST_NAME,
    '13' AS EXPECTED_VALUE,
    COUNT(*)::STRING AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 13 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "owner" = 'ACCOUNTADMIN'
  AND "name" IN (
    'V_LOGIN_HISTORY', 'V_ROLE_GRANT_HISTORY', 'V_PRIVILEGE_ESCALATION_EVENTS',
    'V_PHI_DATA_ACCESS', 'V_MASKING_POLICY_USAGE', 'V_ROW_ACCESS_POLICY_USAGE',
    'V_TAG_CHANGE_HISTORY', 'V_POLICY_CHANGE_HISTORY',
    'V_QUARANTINED_DATA_ACCESS_ATTEMPTS', 'V_42CFR_ACCESS_ATTEMPTS',
    'V_SESSION_HISTORY', 'V_ADMIN_ACTIVITY', 'V_SECURITY_RISK_SCORE'
  );


-- ============================================================
-- SECTION 3: VIEW STRUCTURE VALIDATION
-- ============================================================
-- Validates critical columns exist in each view.
-- ============================================================

-- TC_09_015: V_LOGIN_HISTORY has USER_NAME column
DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_LOGIN_HISTORY;
SELECT
    'TC_09_015' AS TEST_ID,
    'V_LOGIN_HISTORY has USER_NAME column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'USER_NAME';

-- TC_09_016: V_LOGIN_HISTORY has RISK_LEVEL column
DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_LOGIN_HISTORY;
SELECT
    'TC_09_016' AS TEST_ID,
    'V_LOGIN_HISTORY has RISK_LEVEL column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'RISK_LEVEL';

-- TC_09_017: V_PRIVILEGE_ESCALATION_EVENTS has SEVERITY column
DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_PRIVILEGE_ESCALATION_EVENTS;
SELECT
    'TC_09_017' AS TEST_ID,
    'V_PRIVILEGE_ESCALATION_EVENTS has SEVERITY column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'SEVERITY';

-- TC_09_018: V_PHI_DATA_ACCESS has SENSITIVITY_LEVEL column
DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_PHI_DATA_ACCESS;
SELECT
    'TC_09_018' AS TEST_ID,
    'V_PHI_DATA_ACCESS has SENSITIVITY_LEVEL column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'SENSITIVITY_LEVEL';

-- TC_09_019: V_SECURITY_RISK_SCORE has RISK_SCORE column
DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE;
SELECT
    'TC_09_019' AS TEST_ID,
    'V_SECURITY_RISK_SCORE has RISK_SCORE column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'RISK_SCORE';

-- TC_09_020: V_SECURITY_RISK_SCORE has RISK_LEVEL column
DESCRIBE VIEW MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE;
SELECT
    'TC_09_020' AS TEST_ID,
    'V_SECURITY_RISK_SCORE has RISK_LEVEL column' AS TEST_NAME,
    'EXISTS' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'NOT_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'RISK_LEVEL';


-- ============================================================
-- SECTION 4: DATA LATENCY SAFETY CHECK
-- ============================================================
-- Validates views have proper time filters to prevent
-- full table scans of ACCOUNT_USAGE.
-- ============================================================

-- TC_09_021: V_LOGIN_HISTORY has DATEADD time filter
SELECT
    'TC_09_021' AS TEST_ID,
    'V_LOGIN_HISTORY has DATEADD filter' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_LOGIN_HISTORY') LIKE '%DATEADD%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_LOGIN_HISTORY') LIKE '%DATEADD%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_022: V_ROLE_GRANT_HISTORY has DATEADD time filter
SELECT
    'TC_09_022' AS TEST_ID,
    'V_ROLE_GRANT_HISTORY has DATEADD filter' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ROLE_GRANT_HISTORY') LIKE '%DATEADD%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ROLE_GRANT_HISTORY') LIKE '%DATEADD%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_023: V_SESSION_HISTORY has DATEADD time filter
SELECT
    'TC_09_023' AS TEST_ID,
    'V_SESSION_HISTORY has DATEADD filter' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SESSION_HISTORY') LIKE '%DATEADD%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SESSION_HISTORY') LIKE '%DATEADD%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_024: V_ADMIN_ACTIVITY has DATEADD time filter
SELECT
    'TC_09_024' AS TEST_ID,
    'V_ADMIN_ACTIVITY has DATEADD filter' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%DATEADD%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%DATEADD%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;


-- ============================================================
-- SECTION 5: SECURITY GRANT VALIDATION
-- ============================================================
-- Validates proper access control on audit views.
-- ============================================================

-- TC_09_025: COMPLIANCE_OFFICER has SELECT on audit views
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_09_025' AS TEST_ID,
    'COMPLIANCE_OFFICER has SELECT on V_LOGIN_HISTORY' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "name" LIKE '%V_LOGIN_HISTORY%';

-- TC_09_026: COMPLIANCE_OFFICER has SELECT on V_SECURITY_RISK_SCORE
SHOW GRANTS TO ROLE MEDICORE_COMPLIANCE_OFFICER;
SELECT
    'TC_09_026' AS TEST_ID,
    'COMPLIANCE_OFFICER has SELECT on V_SECURITY_RISK_SCORE' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "name" LIKE '%V_SECURITY_RISK_SCORE%';

-- TC_09_027: PLATFORM_ADMIN has SELECT on audit views
SHOW GRANTS TO ROLE MEDICORE_PLATFORM_ADMIN;
SELECT
    'TC_09_027' AS TEST_ID,
    'PLATFORM_ADMIN has SELECT on V_ADMIN_ACTIVITY' AS TEST_NAME,
    'GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'GRANTED' ELSE 'NOT_GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "name" LIKE '%V_ADMIN_ACTIVITY%';


-- ============================================================
-- SECTION 6: NEGATIVE GRANT VALIDATION
-- ============================================================
-- Validates clinical/analyst roles do NOT have audit access.
-- ============================================================

-- TC_09_028: CLINICAL_PHYSICIAN does NOT have SELECT on audit views
SHOW GRANTS TO ROLE MEDICORE_CLINICAL_PHYSICIAN;
SELECT
    'TC_09_028' AS TEST_ID,
    'CLINICAL_PHYSICIAN does NOT have SELECT on V_LOGIN_HISTORY' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "name" LIKE '%V_LOGIN_HISTORY%';

-- TC_09_029: ANALYST_PHI does NOT have SELECT on audit views
SHOW GRANTS TO ROLE MEDICORE_ANALYST_PHI;
SELECT
    'TC_09_029' AS TEST_ID,
    'ANALYST_PHI does NOT have SELECT on V_SECURITY_RISK_SCORE' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "name" LIKE '%V_SECURITY_RISK_SCORE%';

-- TC_09_030: BILLING_SPECIALIST does NOT have SELECT on audit views
SHOW GRANTS TO ROLE MEDICORE_BILLING_SPECIALIST;
SELECT
    'TC_09_030' AS TEST_ID,
    'BILLING_SPECIALIST does NOT have SELECT on V_PHI_DATA_ACCESS' AS TEST_NAME,
    'NOT_GRANTED' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'NOT_GRANTED' ELSE 'GRANTED' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'SELECT'
  AND "name" LIKE '%V_PHI_DATA_ACCESS%';


-- ============================================================
-- SECTION 7: SENSITIVE VIEW VALIDATION
-- ============================================================
-- Validates PHI and 42CFR views have proper tag filters.
-- ============================================================

-- TC_09_031: V_PHI_DATA_ACCESS references TAG_REFERENCES
SELECT
    'TC_09_031' AS TEST_ID,
    'V_PHI_DATA_ACCESS joins TAG_REFERENCES' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_PHI_DATA_ACCESS') LIKE '%TAG_REFERENCES%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_PHI_DATA_ACCESS') LIKE '%TAG_REFERENCES%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_032: V_PHI_DATA_ACCESS filters on MEDICORE_GOVERNANCE_DB tags
SELECT
    'TC_09_032' AS TEST_ID,
    'V_PHI_DATA_ACCESS filters MEDICORE_GOVERNANCE_DB tags' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_PHI_DATA_ACCESS') LIKE '%MEDICORE_GOVERNANCE_DB%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_PHI_DATA_ACCESS') LIKE '%MEDICORE_GOVERNANCE_DB%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_033: V_PHI_DATA_ACCESS filters MEDICORE_% warehouses
SELECT
    'TC_09_033' AS TEST_ID,
    'V_PHI_DATA_ACCESS filters MEDICORE_% warehouses' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_PHI_DATA_ACCESS') LIKE '%MEDICORE_%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_PHI_DATA_ACCESS') LIKE '%MEDICORE_%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_034: V_42CFR_ACCESS_ATTEMPTS filters 42CFR_PART2
SELECT
    'TC_09_034' AS TEST_ID,
    'V_42CFR_ACCESS_ATTEMPTS filters 42CFR_PART2' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_42CFR_ACCESS_ATTEMPTS') LIKE '%42CFR_PART2%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_42CFR_ACCESS_ATTEMPTS') LIKE '%42CFR_PART2%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;


-- ============================================================
-- SECTION 8: ADMIN ACTIVITY VALIDATION
-- ============================================================
-- Validates V_ADMIN_ACTIVITY filters admin roles properly.
-- ============================================================

-- TC_09_035: V_ADMIN_ACTIVITY filters ACCOUNTADMIN
SELECT
    'TC_09_035' AS TEST_ID,
    'V_ADMIN_ACTIVITY filters ACCOUNTADMIN' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%ACCOUNTADMIN%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%ACCOUNTADMIN%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_036: V_ADMIN_ACTIVITY filters SECURITYADMIN
SELECT
    'TC_09_036' AS TEST_ID,
    'V_ADMIN_ACTIVITY filters SECURITYADMIN' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%SECURITYADMIN%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%SECURITYADMIN%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_037: V_ADMIN_ACTIVITY filters SUCCESS status
SELECT
    'TC_09_037' AS TEST_ID,
    'V_ADMIN_ACTIVITY filters EXECUTION_STATUS SUCCESS' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%SUCCESS%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%SUCCESS%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;


-- ============================================================
-- SECTION 9: RISK SCORING LOGIC VALIDATION
-- ============================================================
-- Validates V_SECURITY_RISK_SCORE logic and thresholds.
-- ============================================================

-- TC_09_038: V_SECURITY_RISK_SCORE has admin_usage CTE
SELECT
    'TC_09_038' AS TEST_ID,
    'V_SECURITY_RISK_SCORE has admin_usage CTE' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%admin_usage%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%admin_usage%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_039: V_SECURITY_RISK_SCORE has privilege_escalations CTE
SELECT
    'TC_09_039' AS TEST_ID,
    'V_SECURITY_RISK_SCORE has privilege_escalations CTE' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%privilege_escalations%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%privilege_escalations%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_040: V_SECURITY_RISK_SCORE has failed_logins CTE
SELECT
    'TC_09_040' AS TEST_ID,
    'V_SECURITY_RISK_SCORE has failed_logins CTE' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%failed_logins%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%failed_logins%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_041: V_SECURITY_RISK_SCORE has CRITICAL threshold
SELECT
    'TC_09_041' AS TEST_ID,
    'V_SECURITY_RISK_SCORE has CRITICAL risk level' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%CRITICAL%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%CRITICAL%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_042: V_SECURITY_RISK_SCORE uses 50 points for ACCOUNTADMIN
SELECT
    'TC_09_042' AS TEST_ID,
    'V_SECURITY_RISK_SCORE assigns 50 points' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%50%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SECURITY_RISK_SCORE') LIKE '%50%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;


-- ============================================================
-- SECTION 10: DRIFT DETECTION
-- ============================================================
-- Validates expected view count and no unexpected objects.
-- ============================================================

-- TC_09_043: Phase 09 audit view count equals 13
SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_043' AS TEST_ID,
    'Phase 09 audit view count equals 13' AS TEST_NAME,
    '13' AS EXPECTED_VALUE,
    COUNT(*)::STRING AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = 13 THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" IN (
    'V_LOGIN_HISTORY', 'V_ROLE_GRANT_HISTORY', 'V_PRIVILEGE_ESCALATION_EVENTS',
    'V_PHI_DATA_ACCESS', 'V_MASKING_POLICY_USAGE', 'V_ROW_ACCESS_POLICY_USAGE',
    'V_TAG_CHANGE_HISTORY', 'V_POLICY_CHANGE_HISTORY',
    'V_QUARANTINED_DATA_ACCESS_ATTEMPTS', 'V_42CFR_ACCESS_ATTEMPTS',
    'V_SESSION_HISTORY', 'V_ADMIN_ACTIVITY', 'V_SECURITY_RISK_SCORE'
);

-- TC_09_044: No duplicate view names
SHOW VIEWS IN SCHEMA MEDICORE_GOVERNANCE_DB.AUDIT;
SELECT
    'TC_09_044' AS TEST_ID,
    'No duplicate audit view names' AS TEST_NAME,
    'NO_DUPLICATES' AS EXPECTED_VALUE,
    CASE WHEN COUNT(*) = COUNT(DISTINCT "name") THEN 'NO_DUPLICATES' ELSE 'DUPLICATES_FOUND' END AS ACTUAL_VALUE,
    CASE WHEN COUNT(*) = COUNT(DISTINCT "name") THEN 'PASS' ELSE 'FAIL' END AS TEST_STATUS
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));


-- ============================================================
-- SECTION 11: ACCOUNT_USAGE SOURCE VALIDATION
-- ============================================================
-- Validates views reference proper ACCOUNT_USAGE tables.
-- ============================================================

-- TC_09_045: V_LOGIN_HISTORY references LOGIN_HISTORY
SELECT
    'TC_09_045' AS TEST_ID,
    'V_LOGIN_HISTORY references ACCOUNT_USAGE.LOGIN_HISTORY' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_LOGIN_HISTORY') LIKE '%LOGIN_HISTORY%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_LOGIN_HISTORY') LIKE '%LOGIN_HISTORY%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_046: V_SESSION_HISTORY references SESSIONS
SELECT
    'TC_09_046' AS TEST_ID,
    'V_SESSION_HISTORY references ACCOUNT_USAGE.SESSIONS' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SESSION_HISTORY') LIKE '%SESSIONS%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_SESSION_HISTORY') LIKE '%SESSIONS%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;

-- TC_09_047: V_ADMIN_ACTIVITY references QUERY_HISTORY
SELECT
    'TC_09_047' AS TEST_ID,
    'V_ADMIN_ACTIVITY references ACCOUNT_USAGE.QUERY_HISTORY' AS TEST_NAME,
    'CONTAINS' AS EXPECTED_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%QUERY_HISTORY%'
        THEN 'CONTAINS' 
        ELSE 'MISSING' 
    END AS ACTUAL_VALUE,
    CASE 
        WHEN GET_DDL('VIEW', 'MEDICORE_GOVERNANCE_DB.AUDIT.V_ADMIN_ACTIVITY') LIKE '%QUERY_HISTORY%'
        THEN 'PASS' 
        ELSE 'FAIL' 
    END AS TEST_STATUS;


-- ============================================================
-- SECTION 12: FINAL SUMMARY
-- ============================================================

SELECT
    '=============================================' AS SEPARATOR;

SELECT
    'PHASE 09 AUDIT TEST SUITE COMPLETE' AS STATUS,
    'Total Tests: 47' AS TOTAL_TESTS;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '13 View Existence Tests (TC_09_001 - TC_09_013)' AS SECTION_1;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '1 Ownership Test (TC_09_014)' AS SECTION_2;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '6 Structure Tests (TC_09_015 - TC_09_020)' AS SECTION_3;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '4 Time Filter Tests (TC_09_021 - TC_09_024)' AS SECTION_4;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '3 Positive Grant Tests (TC_09_025 - TC_09_027)' AS SECTION_5;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '3 Negative Grant Tests (TC_09_028 - TC_09_030)' AS SECTION_6;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '4 Sensitive View Tests (TC_09_031 - TC_09_034)' AS SECTION_7;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '3 Admin Activity Tests (TC_09_035 - TC_09_037)' AS SECTION_8;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '5 Risk Scoring Tests (TC_09_038 - TC_09_042)' AS SECTION_9;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '2 Drift Detection Tests (TC_09_043 - TC_09_044)' AS SECTION_10;

SELECT
    'TEST CATEGORIES:' AS CATEGORY,
    '3 Source Validation Tests (TC_09_045 - TC_09_047)' AS SECTION_11;


-- ============================================================
-- END OF PHASE 09 TEST SUITE
-- ============================================================
