USE ROLE ACCOUNTADMIN;


--
CREATE SECRET GOVERNANCE_DB.SECURITY.GITHUB_TOKEN
    TYPE = PASSWORD
    USERNAME = 'ShrinivasVK'
    PASSWORD = '<<GITHUB_PAT_TOKEN_REPLACE_BEFORE_RUNNING>>'
    COMMENT = 'GitHub PAT for medicore-snowflake-platform repository integration';

--
CREATE OR REPLACE API INTEGRATION MEDICORE_GITHUB_INTEGRATION
    API_PROVIDER = GIT_HTTPS_API
    API_ALLOWED_PREFIXES = ('https://github.com/ShrinivasVK/')
    ALLOWED_AUTHENTICATION_SECRETS = (GOVERNANCE_DB.SECURITY.GITHUB_TOKEN)
    ENABLED = TRUE
    COMMENT = 'GitHub API integration for MediCore platform repository';

--
CREATE OR REPLACE GIT REPOSITORY MEDICORE_PLATFORM_REPO
    API_INTEGRATION = MEDICORE_GITHUB_INTEGRATION
    GIT_CREDENTIALS = GOVERNANCE_DB.SECURITY.GITHUB_TOKEN
    ORIGIN = 'https://github.com/YOUR_USERNAME/medicore-snowflake-platform.git'
    COMMENT = 'MediCore Health Systems platform repository';