-- ============================================================
-- MEDICORE HEALTH SYSTEMS - SNOWFLAKE DATA PLATFORM
-- ============================================================
-- Phase 04: Database Structure
-- Script: 04_database_structure.sql
--
-- Description:
--   Creates the 4-tier medallion database architecture for
--   MediCore Health Systems. Implements RAW_DB (Bronze),
--   TRANSFORM_DB (Silver), ANALYTICS_DB (Gold), and AI_READY_DB
--   (Platinum) with appropriate schemas, retention policies,
--   and granular role-based access controls.
--
-- Execution Requirements:
--   - Must be run as ACCOUNTADMIN
--   - Execute statements sequentially from top to bottom
--   - Estimated execution time: 2-3 minutes
--
-- Dependencies:
--   - Phase 02 must be completed (all 17 MEDICORE roles exist)
--   - Phase 03 must be completed (all 4 warehouses exist)
--   - Warehouses: MEDICORE_ETL_WH, MEDICORE_ANALYTICS_WH, MEDICORE_ML_WH
--
-- !! WARNING !!
--   This script creates production databases with specific
--   retention policies. Data retention settings affect Time
--   Travel and Fail-safe costs. Review retention values before
--   execution. Incorrect grants can expose PHI to unauthorized
--   roles or block legitimate data pipeline operations.
--
-- Author: [YOUR_NAME]
-- Date: [YYYY-MM-DD]
-- ============================================================


-- ============================================================
-- SECTION 1: EXECUTION CONTEXT
-- ============================================================

USE ROLE ACCOUNTADMIN;


-- ============================================================
-- SECTION 2: DATABASE CREATION
-- ============================================================
-- Creating 4 databases following the medallion architecture:
--   Bronze (RAW_DB) -> Silver (TRANSFORM_DB) -> Gold (ANALYTICS_DB) -> Platinum (AI_READY_DB)
-- Each database has specific retention policies based on data
-- lifecycle and compliance requirements.
-- ============================================================

-- ------------------------------------------------------------
-- RAW_DB (Bronze Layer)
-- Landing zone for source data exactly as received
-- Maximum retention for HIPAA audit trail compliance
-- ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS RAW_DB
    DATA_RETENTION_TIME_IN_DAYS = 90
    COMMENT = 'Bronze Layer: Landing zone for source data exactly as received from EPIC, CERNER, MEDITECH, and CLAIMS_CLEARINGHOUSE. No transformations applied. Full history preserved. Dirty data, inconsistent formats, and duplicates intentionally retained as-is. 90-day Time Travel for HIPAA audit trail compliance. 7-year logical retention via archive patterns. Primary writers: DATA_ENGINEER, SVC_ETL_LOADER. Primary readers: DATA_ENGINEER only.';

ALTER DATABASE RAW_DB SET DEFAULT_DDL_COLLATION = 'en-ci';

-- ------------------------------------------------------------
-- TRANSFORM_DB (Silver Layer)
-- Cleansed, conformed, and deduplicated data
-- ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS TRANSFORM_DB
    DATA_RETENTION_TIME_IN_DAYS = 30
    COMMENT = 'Silver Layer: Cleansed, conformed, and deduplicated data with business rules applied. PHI still present. Validated formats, referential integrity enforced, dirty data issues resolved. 30-day Time Travel for operational recovery. 3-year logical retention. Primary writers: DATA_ENGINEER. Primary readers: DATA_ENGINEER, DATA_SCIENTIST, COMPLIANCE_OFFICER.';

ALTER DATABASE TRANSFORM_DB SET DEFAULT_DDL_COLLATION = 'en-ci';

-- ------------------------------------------------------------
-- ANALYTICS_DB (Gold Layer)
-- Business-ready aggregated and dimensional models
-- ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB
    DATA_RETENTION_TIME_IN_DAYS = 30
    COMMENT = 'Gold Layer: Business-ready aggregated and dimensional models powering dashboards, reports, and clinical analytics. Masking policies and row access policies enforced (Phase 08). 30-day Time Travel for operational recovery. 3-year logical retention. Primary writers: DATA_ENGINEER via Dynamic Tables. Primary readers: All clinical, billing, analyst, compliance, executive, and application roles.';

ALTER DATABASE ANALYTICS_DB SET DEFAULT_DDL_COLLATION = 'en-ci';

-- ------------------------------------------------------------
-- AI_READY_DB (Platinum Layer)
-- Feature store and ML-optimised datasets
-- ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS AI_READY_DB
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Platinum Layer: Feature store and ML-optimised datasets for model training and inference. Feature-engineered data, normalised for ML, embeddings, and semantic models for Cortex Analyst. 14-day Time Travel (ML iterations are frequent, lower retention acceptable). 2-year logical retention. Primary writers: DATA_SCIENTIST, DATA_ENGINEER. Primary readers: DATA_SCIENTIST, ANALYST_PHI.';

ALTER DATABASE AI_READY_DB SET DEFAULT_DDL_COLLATION = 'en-ci';

-- VERIFICATION: All 4 databases created
SHOW DATABASES LIKE '%_DB';


-- ============================================================
-- SECTION 3: SCHEMA CREATION
-- ============================================================
-- Creating schemas within each database to organize data by
-- domain. Each schema has a descriptive comment explaining
-- its purpose and the types of objects it will contain.
-- ============================================================

-- ------------------------------------------------------------
-- RAW_DB SCHEMAS
-- Source-aligned schemas matching upstream system domains
-- ------------------------------------------------------------

USE DATABASE RAW_DB;

CREATE SCHEMA IF NOT EXISTS CLINICAL
    COMMENT = 'Raw clinical data from source systems (EPIC, CERNER, MEDITECH). Contains: PATIENTS, ENCOUNTERS, LAB_RESULTS, PROVIDERS. Data loaded exactly as received - no transformations. PHI present. Writers: DATA_ENGINEER, SVC_ETL_LOADER. Readers: DATA_ENGINEER only.';

CREATE SCHEMA IF NOT EXISTS BILLING
    COMMENT = 'Raw billing and claims data from CLAIMS_CLEARINGHOUSE. Contains: CLAIMS, CLAIM_LINE_ITEMS. Data loaded exactly as received - no transformations. Financial identifiers present. Writers: DATA_ENGINEER, SVC_ETL_LOADER. Readers: DATA_ENGINEER only.';

CREATE SCHEMA IF NOT EXISTS REFERENCE
    COMMENT = 'Raw reference and dimension data from various sources. Contains: DIM_DEPARTMENTS, DIM_ICD10_CODES. Lookup tables and code sets. No PHI. Writers: DATA_ENGINEER, SVC_ETL_LOADER. Readers: DATA_ENGINEER only.';

CREATE TRANSIENT SCHEMA IF NOT EXISTS AUDIT
    COMMENT = 'Pipeline audit logs and load metadata. Transient schema - no Time Travel or Fail-safe (continuous writes, no recovery needed for individual log records). Contains: load history, row counts, error logs, pipeline run metadata. Writers: DATA_ENGINEER, SVC_ETL_LOADER. Readers: DATA_ENGINEER, COMPLIANCE_OFFICER.';

-- VERIFICATION: RAW_DB schemas created
SHOW SCHEMAS IN DATABASE RAW_DB;

-- ------------------------------------------------------------
-- TRANSFORM_DB SCHEMAS
-- Cleansed data organized by domain with cross-domain utilities
-- ------------------------------------------------------------

USE DATABASE TRANSFORM_DB;

CREATE SCHEMA IF NOT EXISTS CLINICAL
    COMMENT = 'Cleansed clinical entities with validated formats and referential integrity. Derived from RAW_DB.CLINICAL. PHI present. Business rules applied. Writers: DATA_ENGINEER. Readers: DATA_ENGINEER, DATA_SCIENTIST, COMPLIANCE_OFFICER.';

CREATE SCHEMA IF NOT EXISTS BILLING
    COMMENT = 'Cleansed billing entities with validated formats and referential integrity. Derived from RAW_DB.BILLING. Financial identifiers present. Writers: DATA_ENGINEER. Readers: DATA_ENGINEER, DATA_SCIENTIST, COMPLIANCE_OFFICER.';

CREATE SCHEMA IF NOT EXISTS REFERENCE
    COMMENT = 'Validated reference data with enforced constraints. Derived from RAW_DB.REFERENCE. No PHI. Writers: DATA_ENGINEER. Readers: DATA_ENGINEER, DATA_SCIENTIST, COMPLIANCE_OFFICER.';

CREATE SCHEMA IF NOT EXISTS COMMON
    COMMENT = 'Cross-domain shared objects and utilities. Contains: date spine, common transformations, utility functions, shared lookup mappings. No PHI. Writers: DATA_ENGINEER. Readers: DATA_ENGINEER, DATA_SCIENTIST.';

-- VERIFICATION: TRANSFORM_DB schemas created
SHOW SCHEMAS IN DATABASE TRANSFORM_DB;

-- ------------------------------------------------------------
-- ANALYTICS_DB SCHEMAS
-- Business-ready data with role-based access segmentation
-- ------------------------------------------------------------

USE DATABASE ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS CLINICAL
    COMMENT = 'Dimensional models and aggregated clinical views for patient care analytics. PHI present - masking policies enforced (Phase 08). Dynamic Tables from TRANSFORM_DB (Phase 11). Writers: DATA_ENGINEER. Readers: CLINICAL_PHYSICIAN, CLINICAL_NURSE, CLINICAL_READER, ANALYST_PHI, COMPLIANCE_OFFICER, DATA_SCIENTIST, APP_STREAMLIT.';

CREATE SCHEMA IF NOT EXISTS BILLING
    COMMENT = 'Revenue cycle analytics and billing dimensional models. Financial identifiers present - masking policies enforced (Phase 08). Dynamic Tables from TRANSFORM_DB (Phase 11). Writers: DATA_ENGINEER. Readers: BILLING_SPECIALIST, BILLING_READER, ANALYST_PHI, COMPLIANCE_OFFICER, DATA_SCIENTIST, APP_STREAMLIT.';

CREATE SCHEMA IF NOT EXISTS REFERENCE
    COMMENT = 'Governed reference data for all downstream consumers. ICD-10 codes, CPT codes, department master. No PHI. Writers: DATA_ENGINEER. Readers: REFERENCE_READER (and all roles inheriting from it).';

CREATE SCHEMA IF NOT EXISTS EXECUTIVE
    COMMENT = 'Aggregated KPI views for executive dashboards. NO PHI - only aggregated metrics and counts. Safe for EXECUTIVE role and ANALYST_RESTRICTED. Writers: DATA_ENGINEER. Readers: EXECUTIVE, ANALYST_RESTRICTED, ANALYST_PHI, COMPLIANCE_OFFICER, APP_STREAMLIT.';

CREATE SCHEMA IF NOT EXISTS DEIDENTIFIED
    COMMENT = 'Safe Harbor de-identified datasets for external sharing and research. All 18 HIPAA identifiers removed or generalised. Safe for EXT_AUDITOR and ANALYST_RESTRICTED. Writers: DATA_ENGINEER. Readers: EXT_AUDITOR, ANALYST_RESTRICTED, ANALYST_PHI, COMPLIANCE_OFFICER, DATA_SCIENTIST.';

-- VERIFICATION: ANALYTICS_DB schemas created
SHOW SCHEMAS IN DATABASE ANALYTICS_DB;

-- ------------------------------------------------------------
-- AI_READY_DB SCHEMAS
-- ML-optimised data structures for model development
-- ------------------------------------------------------------

USE DATABASE AI_READY_DB;

CREATE SCHEMA IF NOT EXISTS FEATURES
    COMMENT = 'Patient and encounter feature store for ML model inputs. Pre-computed features, normalised values, one-hot encodings. PHI may be present in raw features. Writers: DATA_SCIENTIST, DATA_ENGINEER. Readers: DATA_SCIENTIST, ANALYST_PHI.';

CREATE SCHEMA IF NOT EXISTS TRAINING
    COMMENT = 'Curated ML training datasets with labels and stratified samples. Versioned datasets for model reproducibility. PHI may be present. Writers: DATA_SCIENTIST, DATA_ENGINEER. Readers: DATA_SCIENTIST, ANALYST_PHI.';

CREATE SCHEMA IF NOT EXISTS SEMANTIC
    COMMENT = 'Semantic models for Cortex Analyst natural language queries. Contains YAML definitions, verified queries, and semantic layer metadata. No direct PHI - references governed views. Writers: DATA_SCIENTIST, DATA_ENGINEER. Readers: DATA_SCIENTIST.';

CREATE SCHEMA IF NOT EXISTS EMBEDDINGS
    COMMENT = 'Vector embeddings for clinical NLP and similarity search. Contains: clinical note embeddings, diagnosis embeddings, procedure embeddings. Used with Cortex Vector Search. PHI may be encoded in embeddings. Writers: DATA_SCIENTIST, DATA_ENGINEER. Readers: DATA_SCIENTIST, ANALYST_PHI.';

-- VERIFICATION: AI_READY_DB schemas created
SHOW SCHEMAS IN DATABASE AI_READY_DB;


-- ============================================================
-- SECTION 4: DATABASE AND SCHEMA GRANTS
-- ============================================================
-- Implementing granular access control following the principle
-- of least privilege. Grants are organized by database, then
-- by role within each database section.
-- ============================================================

-- ------------------------------------------------------------
-- RAW_DB GRANTS
-- Most restrictive - only engineering and compliance access
-- ------------------------------------------------------------

USE ROLE ACCOUNTADMIN;

-- MEDICORE_DATA_ENGINEER: Full ownership of RAW_DB schemas
-- Rationale: Data engineers build and maintain all raw data pipelines
GRANT USAGE ON DATABASE RAW_DB TO ROLE MEDICORE_DATA_ENGINEER;
GRANT OWNERSHIP ON SCHEMA RAW_DB.CLINICAL TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RAW_DB.BILLING TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RAW_DB.REFERENCE TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RAW_DB.AUDIT TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;

-- MEDICORE_SVC_ETL_LOADER: Limited write access for automated pipelines
-- Rationale: Service account needs to INSERT data but not DROP or ALTER schemas
GRANT USAGE ON DATABASE RAW_DB TO ROLE MEDICORE_SVC_ETL_LOADER;
GRANT USAGE ON SCHEMA RAW_DB.CLINICAL TO ROLE MEDICORE_SVC_ETL_LOADER;
GRANT USAGE ON SCHEMA RAW_DB.BILLING TO ROLE MEDICORE_SVC_ETL_LOADER;
GRANT USAGE ON SCHEMA RAW_DB.REFERENCE TO ROLE MEDICORE_SVC_ETL_LOADER;
GRANT USAGE ON SCHEMA RAW_DB.AUDIT TO ROLE MEDICORE_SVC_ETL_LOADER;

-- MEDICORE_PLATFORM_ADMIN: Database-level usage for monitoring
-- Rationale: Platform admins need to see database metadata but not query data
GRANT USAGE ON DATABASE RAW_DB TO ROLE MEDICORE_PLATFORM_ADMIN;

-- MEDICORE_COMPLIANCE_OFFICER: Read access for audit and compliance
-- Rationale: Compliance needs to verify data lineage and audit raw source data
GRANT USAGE ON DATABASE RAW_DB TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA RAW_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA RAW_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA RAW_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA RAW_DB.AUDIT TO ROLE MEDICORE_COMPLIANCE_OFFICER;

-- ------------------------------------------------------------
-- TRANSFORM_DB GRANTS
-- Engineering, data science, and compliance access
-- ------------------------------------------------------------

-- MEDICORE_DATA_ENGINEER: Full ownership of TRANSFORM_DB schemas
-- Rationale: Data engineers build and maintain all transformation pipelines
GRANT USAGE ON DATABASE TRANSFORM_DB TO ROLE MEDICORE_DATA_ENGINEER;
GRANT OWNERSHIP ON SCHEMA TRANSFORM_DB.CLINICAL TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TRANSFORM_DB.BILLING TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TRANSFORM_DB.REFERENCE TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TRANSFORM_DB.COMMON TO ROLE MEDICORE_DATA_ENGINEER COPY CURRENT GRANTS;

-- MEDICORE_DATA_SCIENTIST: Read access to all schemas for ML feature development
-- Rationale: Data scientists need cleansed data for feature engineering
GRANT USAGE ON DATABASE TRANSFORM_DB TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA TRANSFORM_DB.CLINICAL TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA TRANSFORM_DB.BILLING TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA TRANSFORM_DB.REFERENCE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA TRANSFORM_DB.COMMON TO ROLE MEDICORE_DATA_SCIENTIST;

-- MEDICORE_COMPLIANCE_OFFICER: Read access for audit and compliance
-- Rationale: Compliance needs to verify transformation logic and data quality
GRANT USAGE ON DATABASE TRANSFORM_DB TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA TRANSFORM_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA TRANSFORM_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA TRANSFORM_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA TRANSFORM_DB.COMMON TO ROLE MEDICORE_COMPLIANCE_OFFICER;

-- MEDICORE_PLATFORM_ADMIN: Database-level usage for monitoring
-- Rationale: Platform admins need to see database metadata but not query data
GRANT USAGE ON DATABASE TRANSFORM_DB TO ROLE MEDICORE_PLATFORM_ADMIN;

-- ------------------------------------------------------------
-- ANALYTICS_DB GRANTS
-- Broadest access - most roles can read from Gold layer
-- Masking policies (Phase 08) will restrict PHI at query time
-- ------------------------------------------------------------

-- MEDICORE_DATA_ENGINEER: CREATE privileges for building analytics objects
-- Rationale: Data engineers create Dynamic Tables and views (Phase 11)
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_DATA_ENGINEER;

-- MEDICORE_CLINICAL_PHYSICIAN: Full clinical access
-- Rationale: Physicians need patient data for treatment decisions
-- Note: Phase 08 will NOT apply masking - physicians see full PHI
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_CLINICAL_PHYSICIAN;
GRANT USAGE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_PHYSICIAN;

-- MEDICORE_CLINICAL_NURSE: Clinical access with unit restrictions
-- Rationale: Nurses need patient data for care coordination
-- Note: Phase 08 will apply masking on financial identifiers
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_CLINICAL_NURSE;
GRANT USAGE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_NURSE;

-- MEDICORE_CLINICAL_READER: Limited clinical access
-- Rationale: Support staff need basic patient identification
-- Note: Phase 08 will apply heavy masking - only name and MRN visible
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_CLINICAL_READER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_READER;

-- MEDICORE_BILLING_SPECIALIST: Full billing access
-- Rationale: Billing staff need claims and coding data
-- Note: Phase 08 will mask clinical notes
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_BILLING_SPECIALIST;
GRANT USAGE ON SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_SPECIALIST;

-- MEDICORE_BILLING_READER: Aggregated billing access
-- Rationale: Financial analysts need billing metrics
-- Note: Phase 08 will restrict to aggregated views only
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_BILLING_READER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_READER;

-- MEDICORE_ANALYST_PHI: Full analytics access with PHI
-- Rationale: Clinical analysts need patient-level data for outcomes research
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_ANALYST_PHI;
GRANT USAGE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_ANALYST_PHI;
GRANT USAGE ON SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_ANALYST_PHI;
GRANT USAGE ON SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_ANALYST_PHI;
GRANT USAGE ON SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_PHI;
GRANT USAGE ON SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_PHI;

-- MEDICORE_ANALYST_RESTRICTED: De-identified and executive schemas only
-- Rationale: Business analysts should not see PHI
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_ANALYST_RESTRICTED;
GRANT USAGE ON SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_RESTRICTED;
GRANT USAGE ON SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_RESTRICTED;

-- MEDICORE_COMPLIANCE_OFFICER: Full read access for compliance monitoring
-- Rationale: Compliance needs to verify policy enforcement and audit data access
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_COMPLIANCE_OFFICER;

-- MEDICORE_EXECUTIVE: Executive schema only (aggregated KPIs, no PHI)
-- Rationale: Executives need high-level metrics, not patient data
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_EXECUTIVE;
GRANT USAGE ON SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_EXECUTIVE;

-- MEDICORE_EXT_AUDITOR: De-identified schema only
-- Rationale: External auditors get pre-staged, de-identified extracts only
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_EXT_AUDITOR;
GRANT USAGE ON SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_EXT_AUDITOR;

-- MEDICORE_APP_STREAMLIT: Application schemas for dashboards
-- Rationale: Streamlit apps need data for visualisations
-- Note: Row access policies (Phase 08) will filter based on invoking user
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_APP_STREAMLIT;

-- MEDICORE_REFERENCE_READER: Reference schema only
-- Rationale: Base role for lookup data (codes, departments)
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_REFERENCE_READER;
GRANT USAGE ON SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_REFERENCE_READER;

-- MEDICORE_DATA_SCIENTIST: Full analytics access for ML development
-- Rationale: Data scientists need access to all analytics data for feature validation
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_DATA_SCIENTIST;

-- MEDICORE_PLATFORM_ADMIN: Database-level usage for monitoring
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE MEDICORE_PLATFORM_ADMIN;

-- ------------------------------------------------------------
-- AI_READY_DB GRANTS
-- Restricted to ML and advanced analytics roles
-- ------------------------------------------------------------

-- MEDICORE_DATA_SCIENTIST: Full ownership of AI_READY_DB schemas
-- Rationale: Data scientists own the ML feature store and training data
GRANT USAGE ON DATABASE AI_READY_DB TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT OWNERSHIP ON SCHEMA AI_READY_DB.FEATURES TO ROLE MEDICORE_DATA_SCIENTIST COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AI_READY_DB.TRAINING TO ROLE MEDICORE_DATA_SCIENTIST COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AI_READY_DB.SEMANTIC TO ROLE MEDICORE_DATA_SCIENTIST COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AI_READY_DB.EMBEDDINGS TO ROLE MEDICORE_DATA_SCIENTIST COPY CURRENT GRANTS;

-- MEDICORE_DATA_ENGINEER: CREATE privileges for populating ML schemas
-- Rationale: Data engineers create base feature tables that data scientists enhance
GRANT USAGE ON DATABASE AI_READY_DB TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA AI_READY_DB.FEATURES TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA AI_READY_DB.TRAINING TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA AI_READY_DB.SEMANTIC TO ROLE MEDICORE_DATA_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA AI_READY_DB.EMBEDDINGS TO ROLE MEDICORE_DATA_ENGINEER;

-- MEDICORE_ANALYST_PHI: Read access to feature and training data
-- Rationale: Clinical analysts may need to validate ML features against source data
GRANT USAGE ON DATABASE AI_READY_DB TO ROLE MEDICORE_ANALYST_PHI;
GRANT USAGE ON SCHEMA AI_READY_DB.FEATURES TO ROLE MEDICORE_ANALYST_PHI;
GRANT USAGE ON SCHEMA AI_READY_DB.TRAINING TO ROLE MEDICORE_ANALYST_PHI;

-- MEDICORE_PLATFORM_ADMIN: Database-level usage for monitoring
GRANT USAGE ON DATABASE AI_READY_DB TO ROLE MEDICORE_PLATFORM_ADMIN;


-- ============================================================
-- SECTION 5: FUTURE GRANTS ON SCHEMAS
-- ============================================================
-- Setting up future grants so that objects created in later
-- phases automatically inherit appropriate privileges without
-- requiring ACCOUNTADMIN intervention.
-- ============================================================

-- ------------------------------------------------------------
-- RAW_DB FUTURE GRANTS
-- ------------------------------------------------------------

-- SVC_ETL_LOADER needs INSERT/UPDATE on future tables for automated pipelines
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA RAW_DB.CLINICAL TO ROLE MEDICORE_SVC_ETL_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA RAW_DB.BILLING TO ROLE MEDICORE_SVC_ETL_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA RAW_DB.REFERENCE TO ROLE MEDICORE_SVC_ETL_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA RAW_DB.AUDIT TO ROLE MEDICORE_SVC_ETL_LOADER;

-- COMPLIANCE_OFFICER needs SELECT on future tables/views for audit
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DB.AUDIT TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW_DB.AUDIT TO ROLE MEDICORE_COMPLIANCE_OFFICER;

-- ------------------------------------------------------------
-- TRANSFORM_DB FUTURE GRANTS
-- ------------------------------------------------------------

-- DATA_SCIENTIST needs SELECT on future tables/views for feature development
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.CLINICAL TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.BILLING TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.REFERENCE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.COMMON TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.CLINICAL TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.BILLING TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.REFERENCE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.COMMON TO ROLE MEDICORE_DATA_SCIENTIST;

-- COMPLIANCE_OFFICER needs SELECT on future tables/views for audit
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSFORM_DB.COMMON TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSFORM_DB.COMMON TO ROLE MEDICORE_COMPLIANCE_OFFICER;

-- ------------------------------------------------------------
-- ANALYTICS_DB FUTURE GRANTS
-- Broadest future grants - many roles need SELECT on analytics
-- ------------------------------------------------------------

-- CLINICAL_PHYSICIAN: SELECT on clinical tables/views
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_PHYSICIAN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_PHYSICIAN;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_PHYSICIAN;

-- CLINICAL_NURSE: SELECT on clinical tables/views (masking policies apply - Phase 08)
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_NURSE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_NURSE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_NURSE;

-- CLINICAL_READER: SELECT on clinical tables/views (heavy masking - Phase 08)
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_READER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_CLINICAL_READER;

-- BILLING_SPECIALIST: SELECT on billing tables/views
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_SPECIALIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_SPECIALIST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_SPECIALIST;

-- BILLING_READER: SELECT on billing tables/views (aggregated views - Phase 08)
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_READER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_BILLING_READER;

-- ANALYST_PHI: SELECT on all schemas
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_PHI;

-- ANALYST_RESTRICTED: SELECT on EXECUTIVE and DEIDENTIFIED only
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_RESTRICTED;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_RESTRICTED;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_RESTRICTED;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_RESTRICTED;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_ANALYST_RESTRICTED;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_ANALYST_RESTRICTED;

-- COMPLIANCE_OFFICER: SELECT on all schemas
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_COMPLIANCE_OFFICER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_COMPLIANCE_OFFICER;

-- EXECUTIVE: SELECT on EXECUTIVE schema only
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_EXECUTIVE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_EXECUTIVE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_EXECUTIVE;

-- EXT_AUDITOR: SELECT on DEIDENTIFIED schema only
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_EXT_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_EXT_AUDITOR;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_EXT_AUDITOR;

-- APP_STREAMLIT: SELECT on CLINICAL, BILLING, EXECUTIVE schemas
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_APP_STREAMLIT;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_APP_STREAMLIT;

-- REFERENCE_READER: SELECT on REFERENCE schema
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_REFERENCE_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_REFERENCE_READER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_REFERENCE_READER;

-- DATA_SCIENTIST: SELECT on all schemas for ML validation
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.CLINICAL TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.BILLING TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.REFERENCE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.EXECUTIVE TO ROLE MEDICORE_DATA_SCIENTIST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ANALYTICS_DB.DEIDENTIFIED TO ROLE MEDICORE_DATA_SCIENTIST;

-- ------------------------------------------------------------
-- AI_READY_DB FUTURE GRANTS
-- ------------------------------------------------------------

-- ANALYST_PHI: SELECT on FEATURES and TRAINING schemas
GRANT SELECT ON FUTURE TABLES IN SCHEMA AI_READY_DB.FEATURES TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AI_READY_DB.TRAINING TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AI_READY_DB.FEATURES TO ROLE MEDICORE_ANALYST_PHI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AI_READY_DB.TRAINING TO ROLE MEDICORE_ANALYST_PHI;


-- ============================================================
-- SECTION 6: VERIFICATION QUERIES
-- ============================================================
-- Comprehensive verification of all Phase 04 components
-- Using INFORMATION_SCHEMA and direct SHOW commands
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Verify all 4 databases exist with correct retention
SELECT DATABASE_NAME, 
       RETENTION_TIME,
       COMMENT
FROM INFORMATION_SCHEMA.DATABASES
WHERE DATABASE_NAME IN ('RAW_DB', 'TRANSFORM_DB', 'ANALYTICS_DB', 'AI_READY_DB')
ORDER BY DATABASE_NAME;

-- Verify schema counts per database
SELECT CATALOG_NAME AS DATABASE_NAME,
       COUNT(*) AS SCHEMA_COUNT
FROM RAW_DB.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME NOT IN ('INFORMATION_SCHEMA', 'PUBLIC')
UNION ALL
SELECT CATALOG_NAME,
       COUNT(*)
FROM TRANSFORM_DB.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME NOT IN ('INFORMATION_SCHEMA', 'PUBLIC')
UNION ALL
SELECT CATALOG_NAME,
       COUNT(*)
FROM ANALYTICS_DB.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME NOT IN ('INFORMATION_SCHEMA', 'PUBLIC')
UNION ALL
SELECT CATALOG_NAME,
       COUNT(*)
FROM AI_READY_DB.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME NOT IN ('INFORMATION_SCHEMA', 'PUBLIC')
ORDER BY DATABASE_NAME;

-- Verify RAW_DB schemas
SHOW SCHEMAS IN DATABASE RAW_DB;

-- Verify TRANSFORM_DB schemas
SHOW SCHEMAS IN DATABASE TRANSFORM_DB;

-- Verify ANALYTICS_DB schemas
SHOW SCHEMAS IN DATABASE ANALYTICS_DB;

-- Verify AI_READY_DB schemas
SHOW SCHEMAS IN DATABASE AI_READY_DB;

-- Verify database grants exist
SHOW GRANTS ON DATABASE RAW_DB;
SHOW GRANTS ON DATABASE TRANSFORM_DB;
SHOW GRANTS ON DATABASE ANALYTICS_DB;
SHOW GRANTS ON DATABASE AI_READY_DB;

-- Verify schema ownership transferred correctly
SHOW GRANTS ON SCHEMA RAW_DB.CLINICAL;
SHOW GRANTS ON SCHEMA TRANSFORM_DB.CLINICAL;
SHOW GRANTS ON SCHEMA ANALYTICS_DB.CLINICAL;
SHOW GRANTS ON SCHEMA AI_READY_DB.FEATURES;

-- Verify future grants configured
SHOW FUTURE GRANTS IN SCHEMA RAW_DB.CLINICAL;
SHOW FUTURE GRANTS IN SCHEMA ANALYTICS_DB.CLINICAL;
SHOW FUTURE GRANTS IN SCHEMA AI_READY_DB.FEATURES;


-- ============================================================
-- SECTION 7: PHASE 04 SUMMARY
-- ============================================================
--
-- DATABASES CREATED: 4
--   - RAW_DB        (Bronze)   - 90-day retention, ETL_WH default
--   - TRANSFORM_DB  (Silver)   - 30-day retention, ETL_WH default
--   - ANALYTICS_DB  (Gold)     - 30-day retention, ANALYTICS_WH default
--   - AI_READY_DB   (Platinum) - 14-day retention, ML_WH default
--
-- SCHEMAS CREATED: 17
--   RAW_DB (4):       CLINICAL, BILLING, REFERENCE, AUDIT (transient)
--   TRANSFORM_DB (4): CLINICAL, BILLING, REFERENCE, COMMON
--   ANALYTICS_DB (5): CLINICAL, BILLING, REFERENCE, EXECUTIVE, DEIDENTIFIED
--   AI_READY_DB (4):  FEATURES, TRAINING, SEMANTIC, EMBEDDINGS
--
-- DATABASE GRANTS: 19
--   - RAW_DB:        4 roles (DATA_ENGINEER, SVC_ETL_LOADER, PLATFORM_ADMIN, COMPLIANCE_OFFICER)
--   - TRANSFORM_DB:  4 roles (DATA_ENGINEER, DATA_SCIENTIST, COMPLIANCE_OFFICER, PLATFORM_ADMIN)
--   - ANALYTICS_DB:  13 roles (all data access roles)
--   - AI_READY_DB:   4 roles (DATA_SCIENTIST, DATA_ENGINEER, ANALYST_PHI, PLATFORM_ADMIN)
--
-- SCHEMA GRANTS: 65+ individual grants
--   - Ownership transfers for DATA_ENGINEER and DATA_SCIENTIST
--   - USAGE grants for all applicable roles
--   - CREATE privileges for engineering roles
--
-- FUTURE GRANTS: 100+ individual grants
--   - SELECT on future TABLES, VIEWS, DYNAMIC TABLES
--   - INSERT/UPDATE for SVC_ETL_LOADER
--
-- PHASE 05 DEPENDENCIES (Resource Monitors):
--   - Databases exist for warehouse assignment monitoring
--   - No resource monitors assigned yet - Phase 05 scope
--
-- PHASE 08 DEPENDENCIES (Data Governance):
--   - Masking policies to be applied to ANALYTICS_DB schemas
--   - Row access policies for role-based data filtering
--   - Tags to be applied for PHI classification
--
-- PHASE 11 DEPENDENCIES (Medallion Architecture):
--   - Dynamic Tables will be created in ANALYTICS_DB schemas
--   - CREATE DYNAMIC TABLE grants already in place
--   - Warehouse references will use MEDICORE_ETL_WH and MEDICORE_ANALYTICS_WH
--
-- ============================================================
-- END OF PHASE 04: DATABASE STRUCTURE
-- ============================================================
